disabled_rules:
  - unneeded_override
  - line_length
  - trailing_whitespace
opt_in_rules:
  - implicit_return
  - private_outlet
  - control_statement
  - empty_count
  - colon
  - comma
included:
  - GalleryApp
excluded:
  - Pods
  - GalleryApp/Application/R.generated.swift

force_cast: warning
force_try:
  severity: warning
type_body_length:
  - 30
  - 40
file_length:
  warning: 300
  error: 400
large_tuple:
  - 3
  - 4
function_parameter_count:
  warning: 3
nesting:
  type_level:
    warning: 2
