# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'GalleryApp' do

  #Common
  pod 'SwiftLint'
  pod 'Kingfisher'
  pod 'R.swift'
 
  # Reactive
  pod 'RxSwift'
  pod 'RxCocoa'

  #Network
  pod 'Moya/RxSwift'
  pod 'ObjectMapper'

end

post_install do |installer|
     installer.pods_project.targets.each do |target|
         target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 13.0
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
         end
     end
end
